### ISSUE TITLE
Poooooster :/

### ISSUE THREAD

**Issue by JPT580** [teamteamteam/SpaceScooter#20]
Ohne Poster keine Postermesse.

**Comment by JPT580** [comment]
Ersten Entwurf mal so hingeklatscht.

**Comment by JPT580** [comment]
Kommt noch jemand heute?

**Comment by lubiana** [comment]
Bin grad hart am lernen. Bis wann muss das Poster fertig sein? Mein IRC client kämpft grad mit freenode.

**Comment by JPT580** [comment]
Absolute Deadline ist der 23.01.
Bevorzugte Abgabe wäre: davor ;)

**Comment by lubiana** [comment]
Ok, ich schreibe halt am Montag tinf. Danach schaue ich mir das an. Bin auch wieder im irc

**Comment by JPT580** [comment]
abgehakt.
